services:
  - type: web
    name: domitory-buying-platform-crawler
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium --with-deps
    startCommand: gunicorn app:app --workers 1 --bind 0.0.0.0:$PORT
    plan: free